version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lu_estilo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    volumes:
      - .:/app   # <- isso mapeia sua pasta local pro container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/lu_estilo
    ports:
      - "8000:8000"

volumes:
  postgres_data:
